### ISSUE TITLE
Ask NVS/AVTT for training for interested DACs/ADMT members on how best to access NVS Argo ref tables via API

### ISSUE THREAD

**Issue by cgourcuf** [OneArgo/ArgoVocabs#140]

**Comment by tcarval** [comment]
Machines can access the NVS database through the SPARQL endpoint.
https://vocab.nerc.ac.uk/ SPARQL  
Demo code in a Jupyter Notebook file was added to the [ArgoVocabs repo](https://github.com/nvs-vocabs/ArgoVocabs/blob/master/m2m_NVS_sparql.ipynb)
[m2m_NVS_sparql.ipynb](https://github.com/OneArgo/ArgoVocabs/blob/master/m2m_NVS_sparql.ipynb)

**Comment by gmaze** [comment]
No need to learn the API ! **argopy** has a great feature for this !

It's all explained in here:
https://argopy.readthedocs.io/en/latest/metadata_fetching.html#reference-tables

Just ask for a table ID, and get it as Panda dataframe ...

```python
from argopy import ArgoNVSReferenceTables

NVS = ArgoNVSReferenceTables()

NVS.tbl('R01')
```

and if you don't know the ID of the table, just look for it:
```python
id_list = NVS.search('sensor')
[NVS.tbl_name(id) for id in id_list]

[('SENSOR',
  'Terms describing sensor types mounted on Argo floats. Argo netCDF variable SENSOR is populated by R25 altLabel.',
  'http://vocab.nerc.ac.uk/collection/R25/current/'),
 ('SENSOR_MAKER',
  'Terms describing developers and manufacturers of sensors mounted on Argo floats. Argo netCDF variable SENSOR_MAKER is populated by R26 altLabel.',
  'http://vocab.nerc.ac.uk/collection/R26/current/'),
 ('SENSOR_MODEL',
  'Terms listing models of sensors mounted on Argo floats. Note: avoid using the manufacturer name and sensor firmware version in new entries when possible. Argo netCDF variable SENSOR_MODEL is populated by R27 altLabel.',
  'http://vocab.nerc.ac.uk/collection/R27/current/')]
```
